run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign

linters-settings:
  errcheck:
    check-type-assertions: false

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10