# Configuração simplificada do golangci-lint
run:
  timeout: 5m
  tests: false

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - ineffassign
    - typecheck

issues:
  max-issues-per-linter: 50
  max-same-issues: 10