# Configuração do golangci-lint para Direito Lux

run:
  timeout: 5m
  tests: false
  skip-dirs:
    - bin
    - vendor
    - testdata
  skip-files:
    - ".*_test.go"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
  disable:
    - unused
    - gosec
    - dupl
    - gocyclo
    - gocognit

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    enable-all: false
  gofmt:
    simplify: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
    - path: cmd/
      linters:
        - gocyclo
  max-issues-per-linter: 50
  max-same-issues: 10