# Docker Compose para DESENVOLVIMENTO
# Apenas infraestrutura: Keycloak, PostgreSQL, Redis, Nginx
# API Go roda localmente para desenvolvimento rápido

version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: direito-lux-postgres-dev
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expostas para acesso local
    networks:
      - direito-lux-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: direito-lux-redis-dev
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"  # Expostas para acesso local
    networks:
      - direito-lux-dev
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-1:
    image: quay.io/keycloak/keycloak:26.0
    container_name: direito-lux-keycloak-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_CACHE: ispn
      KC_CACHE_CONFIG_FILE: cache-ispn.xml
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --cache-config-file=cache-ispn.xml
    volumes:
      - ./keycloak/cache-ispn.xml:/opt/keycloak/conf/cache-ispn.xml
      - ./keycloak/themes:/opt/keycloak/themes
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - direito-lux-dev
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  direito-lux-dev:
    driver: bridge