_format_version: "3.0"
_transform: true

# Direito Lux - Kong Configuration
# API Gateway with multi-tenant rate limiting and security

services:
  # Direito Lux API Service
  - name: direito-lux-api
    url: http://direito-lux-api:9001
    protocol: http
    port: 9001
    path: /
    retries: 5
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    tags:
      - direito-lux
      - api

    routes:
      # Health check route (public)
      - name: health-check
        paths:
          - /health
        strip_path: false
        tags:
          - public
          - health
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - X-Auth-Token
                - X-Request-ID
                - Authorization
              exposed_headers:
                - X-Auth-Token
                - X-Request-ID
              credentials: true
              max_age: 3600

      # API v1 routes (protected)
      - name: api-v1
        paths:
          - /api/v1
        strip_path: false
        tags:
          - api
          - v1
        plugins:
          - name: cors
            config:
              origins:
                - "*"
              methods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              headers:
                - Accept
                - Accept-Version
                - Content-Length
                - Content-MD5
                - Content-Type
                - Date
                - X-Auth-Token
                - X-Request-ID
                - Authorization
                - X-Tenant-ID
              exposed_headers:
                - X-Auth-Token
                - X-Request-ID
                - X-Tenant-ID
              credentials: true
              max_age: 3600

          # JWT validation
          - name: jwt
            config:
              uri_param_names:
                - jwt
              cookie_names:
                - jwt
              header_names:
                - authorization
              claims_to_verify:
                - exp
              key_claim_name: iss
              secret_is_base64: false
              run_on_preflight: false

          # Rate limiting by tenant
          - name: rate-limiting-advanced
            config:
              limit:
                - 100
              window_size:
                - 60
              identifier: consumer
              dictionary_name: direito-lux-ratelimit
              sync_rate: -1
              namespace: direito-lux
              strategy: local
              hide_client_headers: false

          # Request size limiting
          - name: request-size-limiting
            config:
              allowed_payload_size: 10
              size_unit: megabytes

          # Request/Response transformer for tenant context
          - name: request-transformer
            config:
              add:
                headers:
                  - X-Kong-Proxy:true
                  - X-API-Version:v1
              remove:
                headers:
                  - X-Internal-Header

  # Keycloak Service (for token introspection)
  - name: keycloak-service
    url: http://keycloak-1:8080
    protocol: http
    port: 8080
    path: /
    retries: 3
    connect_timeout: 30000
    write_timeout: 30000
    read_timeout: 30000
    tags:
      - keycloak
      - auth

    routes:
      - name: keycloak-public
        paths:
          - /auth
        strip_path: false
        tags:
          - auth
          - public

# Upstream targets for load balancing
upstreams:
  - name: direito-lux-api.upstream
    algorithm: round-robin
    slots: 10000
    healthchecks:
      active:
        type: http
        http_path: /health
        healthy:
          interval: 10
          successes: 3
          http_statuses:
            - 200
            - 201
            - 202
            - 203
            - 204
        unhealthy:
          interval: 5
          http_failures: 3
          timeouts: 3
          tcp_failures: 3
          http_statuses:
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505
      passive:
        type: http
        healthy:
          successes: 5
          http_statuses:
            - 200
            - 201
            - 202
            - 203
            - 204
        unhealthy:
          http_failures: 3
          timeouts: 3
          tcp_failures: 3
          http_statuses:
            - 500
            - 501
            - 502
            - 503
            - 504
            - 505

    targets:
      - target: direito-lux-api:9001
        weight: 100
        tags:
          - primary

# Global plugins
plugins:
  # Prometheus metrics
  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

  # Request ID generation
  - name: correlation-id
    config:
      header_name: X-Request-ID
      generator: uuid
      echo_downstream: true

  # Security headers
  - name: response-transformer
    config:
      add:
        headers:
          - X-Frame-Options:DENY
          - X-Content-Type-Options:nosniff
          - X-XSS-Protection:1; mode=block
          - Strict-Transport-Security:max-age=31536000; includeSubDomains

  # Bot detection
  - name: bot-detection
    config:
      allow:
        - GoogleBot
        - BingBot
      deny:
        - "*"

  # IP restriction (configure for production)
  # - name: ip-restriction
  #   config:
  #     allow:
  #       - 192.168.0.0/16
  #       - 10.0.0.0/8