global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'direito-lux'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Kong metrics
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
        labels:
          service: 'kong'
    metrics_path: '/metrics'

  # OPA metrics
  - job_name: 'opa'
    static_configs:
      - targets: ['opa:8282']
        labels:
          service: 'opa'
    metrics_path: '/metrics'

  # Direito Lux API metrics
  - job_name: 'direito-lux-api'
    static_configs:
      - targets: ['direito-lux-api:9001']
        labels:
          service: 'direito-lux-api'
    metrics_path: '/metrics'

  # Keycloak metrics
  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak-1:8080', 'keycloak-2:8080']
        labels:
          service: 'keycloak'
    metrics_path: '/metrics'

  # PostgreSQL exporter (if configured)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'

  # Redis exporter (if configured)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node'