# Direito Lux - Development Environment Values
# Configuração Helm para ambiente de desenvolvimento

global:
  environment: dev
  domain: dev.direito-lux.com.br
  registry: gcr.io/direito-lux-dev
  
  # Configurações de banco
  database:
    host: 127.0.0.1:5432
    name: direito_lux_dev
    user: postgres
    ssl: disable
  
  # Redis
  redis:
    host: 127.0.0.1:6379
    password: redis123
  
  # Observabilidade
  monitoring:
    enabled: true
    namespace: monitoring
  
  # Recursos padrão para DEV (menores)
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# ========== SERVIÇOS ==========

# Serviço de Autenticação
auth:
  enabled: true
  name: direito-lux-auth
  
  image:
    repository: gcr.io/direito-lux-dev/auth
    tag: latest
    pullPolicy: Always
  
  replicas: 1
  
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  
  env:
    - name: APP_ENV
      value: development
    - name: DB_HOST
      value: "127.0.0.1"
    - name: DB_PORT
      value: "5432"
    - name: DB_NAME
      value: direito_lux_dev
    - name: REDIS_HOST
      value: "127.0.0.1:6379"
    - name: LOG_LEVEL
      value: debug

# Serviço de Consulta Jurídica
consulta:
  enabled: true
  name: direito-lux-consulta
  
  image:
    repository: gcr.io/direito-lux-dev/consulta
    tag: latest
    pullPolicy: Always
  
  replicas: 1
  
  service:
    type: ClusterIP
    port: 9002
    targetPort: 9002
  
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  env:
    - name: APP_ENV
      value: development
    - name: PORT
      value: "9002"
    - name: ELASTICSEARCH_URL
      value: http://elasticsearch:9200
    - name: LOG_LEVEL
      value: debug

# Serviço de IA Jurídica
ia-juridica:
  enabled: true
  name: direito-lux-ia
  
  image:
    repository: gcr.io/direito-lux-dev/ia-juridica
    tag: latest
    pullPolicy: Always
  
  replicas: 1
  
  service:
    type: ClusterIP
    port: 9003
    targetPort: 9003
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi
  
  env:
    - name: DIREITO_LUX_IA_ENVIRONMENT
      value: development
    - name: DIREITO_LUX_IA_PORT
      value: "9003"
    - name: DIREITO_LUX_IA_CHROMA_HOST
      value: chromadb
    - name: DIREITO_LUX_IA_REDIS_HOST
      value: redis
    - name: DIREITO_LUX_IA_LOG_LEVEL
      value: DEBUG
  
  # Secrets para IA
  secrets:
    - name: DIREITO_LUX_IA_OPENAI_API_KEY
      secretName: openai-secret
      secretKey: api-key

# ========== DEPENDÊNCIAS ==========

# Keycloak
keycloak:
  enabled: true
  
  replicas: 1
  
  image:
    repository: quay.io/keycloak/keycloak
    tag: 22.0
  
  service:
    type: ClusterIP
    port: 8080
  
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  
  env:
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-secret
          key: admin-password
    - name: KC_DB
      value: postgres

# Kong Gateway
kong:
  enabled: true
  
  image:
    repository: kong
    tag: 3.4
  
  service:
    type: LoadBalancer
    ports:
      proxy: 80
      proxyTls: 443
      admin: 8001
  
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi

# ChromaDB (Vector Database)
chromadb:
  enabled: true
  
  image:
    repository: chromadb/chroma
    tag: latest
  
  service:
    type: ClusterIP
    port: 8000
  
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  
  persistence:
    enabled: true
    size: 10Gi
    storageClass: standard

# Redis
redis:
  enabled: true
  
  image:
    repository: redis
    tag: 7-alpine
  
  service:
    type: ClusterIP
    port: 6379
  
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  
  persistence:
    enabled: true
    size: 5Gi

# ========== INGRESS ==========

ingress:
  enabled: true
  className: nginx
  
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  
  hosts:
    - host: dev.direito-lux.com.br
      paths:
        - path: /api/v1/auth
          pathType: Prefix
          service:
            name: direito-lux-auth
            port: 8080
        - path: /api/v1/consulta
          pathType: Prefix
          service:
            name: direito-lux-consulta
            port: 9002
        - path: /api/v1/ia
          pathType: Prefix
          service:
            name: direito-lux-ia
            port: 9003
        - path: /auth
          pathType: Prefix
          service:
            name: keycloak
            port: 8080
  
  tls:
    - secretName: dev-tls
      hosts:
        - dev.direito-lux.com.br

# ========== MONITORAMENTO ==========

monitoring:
  enabled: true
  
  # Prometheus
  prometheus:
    enabled: true
    retention: 7d
    storageSize: 10Gi
  
  # Grafana
  grafana:
    enabled: true
    adminPassword: admin123
  
  # AlertManager
  alertmanager:
    enabled: true
    
  # ServiceMonitor para scraping
  serviceMonitors:
    - name: direito-lux-services
      labels:
        app: direito-lux
      endpoints:
        - port: metrics
          interval: 30s

# ========== AUTO SCALING ==========

autoscaling:
  enabled: false  # Desabilitado em DEV
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# ========== NETWORK POLICIES ==========

networkPolicies:
  enabled: true
  
  # Política restritiva para DEV
  policies:
    - name: deny-all
      podSelector: {}
      policyTypes:
        - Ingress
        - Egress
    
    - name: allow-internal
      podSelector:
        matchLabels:
          app: direito-lux
      ingress:
        - from:
          - podSelector:
              matchLabels:
                app: direito-lux