# OPA Configuration for Direito Lux

decision_logs:
  console: true

status:
  console: true

# Health check configuration
health:
  enabled: true

# Performance tuning
caching:
  inter_query_builtin_cache:
    max_size_bytes: 10000000

# Data sources for policies
labels:
  app: "direito-lux"
  version: "v1"